### ISSUE TITLE
Black listed

### ISSUE THREAD

**Issue by miguelhentoux** [Sjord/growatt_api_client#34]
Hello,
Everything was running fine, until this week. I think I was blacklisted with my local machine, do you know what I could do?
I can't login with the api anymore (I tested 3 different logins and they worked in UI).

```
api = GrowattApi()
response = api.login(user_login, password)
```
Then I got this error:
`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Then I run in this way to get the response text:
```
response = api.session.post(
    api.get_url("newLoginAPI.do"),
    data={"userName": user_login, "password": password_md5},
)
response.text
```
response:
`'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>403 Forbidden</title></head><body><h1>403 Forbidden</h1><p>You don\'t have permission to access the URL on this server.</p><p>denied by UA ACL = blacklist</p><hr/>Powered by Tengine <br/>CDN Request Id: 4f85b19f16688496115357515e</body></html>'`

**Comment by Sjord** [comment]
Yes, Growatt seems to block certain user agents. So a solution would be to change the user agent, but then Growatt changes their blacklist, etc. See also:

* [Issue with User-Agent field from #36 is happening again · Issue #38 · indykoning/PyPi\_GrowattServer](https://github.com/indykoning/PyPi_GrowattServer/issues/38)
* [Library is operating inconsistently after recent changes on the Growatt server side · Issue #36 · indykoning/PyPi\_GrowattServer](https://github.com/indykoning/PyPi_GrowattServer/issues/36)
